### ISSUE TITLE
Only syncs once, requires deletion of DB to pull new transaction

### ISSUE THREAD

**Issue by JackPala** [justinforlenza/firefly-plaid-connector#1]
In Polled mode, initial sync pulls all transactions perfectly, however new transactions fail to pull without any known log output of errors. Upon deleting the import-db.sqlite3 file, and restarting the container, the new transactions pull correctly, however doing so results in duplicate transactions from the transactions already imported from the initial sync

**Comment by justinforlenza** [comment]
Sorry this is an outdated Fork of [GeorgeHahn/firefly-plaid-connector](https://github.com/GeorgeHahn/firefly-plaid-connector), please check their repo for any updates/issues
